---
title: "git_00"
author: "Jeannet Cendejas"
date: "Sept 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

And cannot pleasures, while they last,  
Be actual unless, when past,  
They leave us shuddering and aghast,  
With anguish smarting?  
And cannot friends be firm and fast,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;    

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

When my hopes fade  
And my dreams die.  
And I find no answer  
By asking why.  
I just keep on trusting  
And hang on to my faith.  
Because God is just  
He never makes mistakes.  
Should the storms come  
And trials I must face.  
When I find no solution  
I rest in God's grace.  
When life seems unfair  
And more than I can take.  
I look up to the Father  
He never makes mistakes.  
God sees our struggles  
And every bend in the road.  
But no mistake is ever made  
Cause He weighs every load  
